version: '2.1'
services:
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk

 kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
    container_name: kibana
    hostname: kibana
    ports:
           - 5601:5601
    networks:
           - elk
    depends_on:
      - elasticsearch

 user:
    image: ahmed/basic-user-webservice2:latest
    ports:
    - 8080:8080
    networks:
       - elk
    depends_on:
       - elasticsearch
    hostname: user
    container_name: user
    environment:
    - SPRING_PROFILES_ACTIVE=development
    - CONFIG_SERVER_URL=http://config:8888

networks:
  elk:
    driver: bridge
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local